### ISSUE TITLE
大佬看一下此语言有无希望

### ISSUE THREAD

**Issue by Jamesqiu-123** [awathefox/DNAnother#2]
https://code.xueersi.com/home/project/detail?lang=code&pid=23765947&version=cpp&form=cpp&langType=cpp，大佬看一下有无希望。

**Comment by Aw-XwX** [comment]
柠檬什么时候酸啊
学而思xxs不要在我个人项目下乱开issue好吗
创谢，，，
至于这个语言是什么东西，我暂且蒙在程序穀里。

**Comment by FurryR** [comment]
柠檬什么时候酸啊
学而思xxs不要在我个人项目下发无关issue好吗
至于这个语言是什么东西，我暂且蒙在程序榖里。

**Comment by Jamesqiu-123** [comment]
> 柠檬什么时候酸啊
> 学而思xxs不要在我个人项目下发无关issue好吗
> 至于这个语言是什么东西，我暂且蒙在程序榖里。

大佬，找错人了，抱歉
